services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 87f5ce84d66c6ca661f614213858b0b4
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - /data/stack-2/pgdata:/var/lib/postgresql/data/pgdata

  minio:
    image: minio/minio:latest
    command: server /storage --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: M1HRD8PLVB3AUNWJII4WBXII
      MINIO_ROOT_PASSWORD: ONg70JbjewoFnK9h7RRR4V0m2whzOLiRHsXyreyk4yWJzk7g
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /data/stack-2/minio:/storage

  dm-engine:
    image: dhanmitra/dm-engine:dev
    ports:
      - "8001:8000"
    env_file: "dm-engine.env"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
